version: '3.8'

services:
  spring-backend:
    container_name: health_monitor_spring_backend
    build:
      context: ./health_monitor_spring
      dockerfile: dockerfile
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/health
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - net1

  angular-frontend:
    container_name: health_monitor_angular_frontend
    build:
      context: ./health_monitor_angular
      dockerfile: dockerfile
    ports:
      - "4200:4200"
    networks:
      - net1

  flutter-web:
    container_name: health_monitor_flutter_web
    build:
      context: ./health_monitor_flutter
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - net1

  flask-backend:
    container_name: health_monitor_flask_backend
    build:
      context: ./health_monitor_flask
      dockerfile: dockerfile
    ports:
      - "8000:8000"  # Expose Flask backend on port 8000
    depends_on:
      - ollama
    environment:
      - LLAMA_ENDPOINT=http://ollama:11434/v1/chat/completions
    volumes:
      - ./health_monitor_flask:/app
    restart: always
    networks:
      - net1

  ollama:
    container_name: health_monitor_ollama
    image: ollama/ollama
    ports:
      - "11434:11434"  # Expose Ollama service
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    networks:
      - net1

  db:
    container_name: health_monitor_db
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: health
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3308:3306"
    volumes:
      - health_db_data:/var/lib/mysql
    networks:
      - net1

networks:
  net1:
    driver: bridge

volumes:
  health_db_data:
  ollama_data:
